import { useEffect, useMemo, useState } from "react";
import { Check, Link2, RefreshCw, UserPlus } from "lucide-react";
import { ActionForm, Badge, Card, DataTable, EmptyState, FormField, PageHeader, Tabs } from "../components/ui";
import { api, json } from "../lib/api";
import { formatDate, isoToday, plusDays } from "../lib/format";
import { useLanguage } from "../lib/i18n";
import { validateBilingual } from "../lib/validation";
import type { AcademicYear, Course, ExamPeriod, Offering, Staff } from "../types";

export function AcademicPage() {
  const { language, pick } = useLanguage(); const [tab, setTab] = useState("years"); const [years, setYears] = useState<AcademicYear[]>([]); const [courses, setCourses] = useState<Course[]>([]); const [offerings, setOfferings] = useState<Offering[]>([]); const [staff, setStaff] = useState<Staff[]>([]); const [periods, setPeriods] = useState<ExamPeriod[]>([]); const [loading, setLoading] = useState(true);
  const currentYear = useMemo(() => years.find(x => x.isCurrent) || years[0], [years]);
  const load = async () => { setLoading(true); try { const [nextYears, nextCourses, nextStaff] = await Promise.all([api<AcademicYear[]>("/api/catalog/academic-years"), api<Course[]>("/api/catalog/courses"), api<Staff[]>("/api/catalog/staff")]); setYears(nextYears); setCourses(nextCourses); setStaff(nextStaff); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  useEffect(() => { if (!currentYear) return; Promise.all([api<Offering[]>(`/api/catalog/offerings?academicYearId=${currentYear.id}`), api<ExamPeriod[]>(`/api/catalog/exam-periods?academicYearId=${currentYear.id}`)]).then(([o,p]) => { setOfferings(o); setPeriods(p); }); }, [currentYear?.id]);
  const [year, setYear] = useState({ name: "2026-2027", startsOn: "2026-09-01", endsOn: "2027-08-31", firstSemesterStartsOn: "2026-09-20", firstSemesterEndsOn: "2027-01-31", secondSemesterStartsOn: "2027-02-15", secondSemesterEndsOn: "2027-07-15" });
  const [holiday, setHoliday] = useState({ date: isoToday(), reason: "" });
  const [course, setCourse] = useState({ code: "", nameArabic: "", nameEnglish: "", studyYear: "1", semesterNumber: "1", theoreticalSessionsPerWeek: "1", practicalSessionsPerDivisionPerWeek: "1", requiresProjector: false, requiresLab: true });
  const [offering, setOffering] = useState({ courseId: "", semesterId: "" }); const [assignment, setAssignment] = useState({ offeringId: "", staffUserId: "", role: "Professor" });
  const [exam, setExam] = useState({ nameArabic: "", nameEnglish: "", startsOn: isoToday(), endsOn: plusDays(14), isRetake: false }); const [syncYear, setSyncYear] = useState("1");
  const createYear = async () => { await api("/api/academic/years", { method: "POST", ...json(year) }); await load(); };
  const setCurrent = async (id: string) => { await api(`/api/academic/years/${id}/current`, { method: "PUT" }); await load(); };
  const addHoliday = async () => { if (!currentYear) return; await api(`/api/academic/years/${currentYear.id}/non-teaching-days`, { method: "POST", ...json(holiday) }); setHoliday(x => ({ ...x, reason: "" })); };
  const createCourse = async () => { validateBilingual(course.nameArabic, course.nameEnglish, "name"); await api("/api/academic/courses", { method: "POST", ...json({ ...course, studyYear: Number(course.studyYear), semesterNumber: Number(course.semesterNumber), theoreticalSessionsPerWeek: Number(course.theoreticalSessionsPerWeek), practicalSessionsPerDivisionPerWeek: Number(course.practicalSessionsPerDivisionPerWeek) }) }); setCourse(x => ({ ...x, code: "", nameArabic: "", nameEnglish: "" })); await load(); };
  const createOffering = async () => { if (!currentYear) return; await api("/api/academic/offerings", { method: "POST", ...json({ courseId: offering.courseId, academicYearId: currentYear.id, semesterId: offering.semesterId }) }); setOffering({ courseId: "", semesterId: "" }); setOfferings(await api(`/api/catalog/offerings?academicYearId=${currentYear.id}`)); };
  const assign = async () => { await api(`/api/academic/offerings/${assignment.offeringId}/staff`, { method: "POST", ...json({ staffUserId: assignment.staffUserId, role: assignment.role }) }); if (currentYear) setOfferings(await api(`/api/catalog/offerings?academicYearId=${currentYear.id}`)); };
  const createExam = async () => { if (!currentYear) return; validateBilingual(exam.nameArabic, exam.nameEnglish, "name"); await api("/api/academic/exam-periods", { method: "POST", ...json({ academicYearId: currentYear.id, ...exam }) }); setPeriods(await api(`/api/catalog/exam-periods?academicYearId=${currentYear.id}`)); };
  const closeExam = async (id: string) => { await api(`/api/academic/exam-periods/${id}/close`, { method: "PUT" }); if (currentYear) setPeriods(await api(`/api/catalog/exam-periods?academicYearId=${currentYear.id}`)); };
  const sync = async () => { if (!currentYear) return; await api(`/api/academic/years/${currentYear.id}/enrollments/sync/${syncYear}`, { method: "POST" }); };
  return <><PageHeader eyebrow={pick("بنية البرنامج", "Program structure")} title={pick("الشؤون الأكاديمية", "Academic administration")} description={pick("أدر السنة والمقررات والتكليفات والدورات الامتحانية من مكان واحد.", "Manage years, courses, assignments, and exam periods in one place.")} actions={<button className="button button-secondary" onClick={load}><RefreshCw size={17} />{pick("تحديث", "Refresh")}</button>} /><Tabs active={tab} onChange={setTab} tabs={[{ id:"years", label:pick("السنوات", "Years") }, { id:"courses", label:pick("المقررات", "Courses") }, { id:"offerings", label:pick("الطرح والتكليف", "Offerings & staff") }, { id:"exams", label:pick("الامتحانات", "Exam periods") }]} />{loading ? <div className="loading-block">Loading…</div> : <>
    {tab === "years" && <div className="two-panel"><Card title={pick("السنوات الأكاديمية", "Academic years")}>{years.length ? <div className="stack-list">{years.map(x => <div key={x.id} className="stack-row"><div><strong>{x.name}</strong><span>{formatDate(x.startsOn, language)} — {formatDate(x.endsOn, language)}</span><small>{x.semesters.map(s => `${pick("فصل", "Semester")} ${s.number}`).join(" · ")}</small></div>{x.isCurrent ? <Badge tone="success">{pick("الحالية", "Current")}</Badge> : <button className="button button-small" onClick={() => setCurrent(x.id)}>{pick("تعيين كحالية", "Make current")}</button>}</div>)}</div> : <EmptyState title={pick("أنشئ السنة الأولى", "Create the first academic year")} />}</Card><Card title={pick("سنة أكاديمية جديدة", "New academic year")}><ActionForm onSubmit={createYear} submitLabel={pick("إنشاء السنة", "Create year")}><FormField label={pick("الاسم", "Name")}><input required value={year.name} onChange={e => setYear(x => ({...x,name:e.target.value}))} /></FormField><div className="two-columns"><FormField label={pick("بداية السنة", "Year starts")}><input type="date" required value={year.startsOn} onChange={e => setYear(x => ({...x,startsOn:e.target.value}))} /></FormField><FormField label={pick("نهاية السنة", "Year ends")}><input type="date" required value={year.endsOn} onChange={e => setYear(x => ({...x,endsOn:e.target.value}))} /></FormField><FormField label={pick("بداية الفصل الأول", "Semester 1 starts")}><input type="date" required value={year.firstSemesterStartsOn} onChange={e => setYear(x => ({...x,firstSemesterStartsOn:e.target.value}))} /></FormField><FormField label={pick("نهاية الفصل الأول", "Semester 1 ends")}><input type="date" required value={year.firstSemesterEndsOn} onChange={e => setYear(x => ({...x,firstSemesterEndsOn:e.target.value}))} /></FormField><FormField label={pick("بداية الفصل الثاني", "Semester 2 starts")}><input type="date" required value={year.secondSemesterStartsOn} onChange={e => setYear(x => ({...x,secondSemesterStartsOn:e.target.value}))} /></FormField><FormField label={pick("نهاية الفصل الثاني", "Semester 2 ends")}><input type="date" required value={year.secondSemesterEndsOn} onChange={e => setYear(x => ({...x,secondSemesterEndsOn:e.target.value}))} /></FormField></div></ActionForm>{currentYear && <div className="sub-form"><h3>{pick("يوم بلا تدريس", "Non-teaching day")}</h3><ActionForm onSubmit={addHoliday} submitLabel={pick("إضافة", "Add")} className="inline-form"><FormField label={pick("التاريخ", "Date")}><input type="date" required value={holiday.date} onChange={e => setHoliday(x => ({...x,date:e.target.value}))} /></FormField><FormField label={pick("السبب", "Reason")}><input required value={holiday.reason} onChange={e => setHoliday(x => ({...x,reason:e.target.value}))} /></FormField></ActionForm></div>}</Card></div>}
    {tab === "courses" && <><Card title={pick("مقرر جديد", "New course")}><ActionForm onSubmit={createCourse} submitLabel={pick("إضافة المقرر", "Add course")}><div className="form-grid"><FormField label={pick("الرمز", "Code")}><input required value={course.code} onChange={e => setCourse(x => ({...x,code:e.target.value.toUpperCase()}))} /></FormField><FormField label={pick("الاسم بالعربية", "Arabic name")}><input required value={course.nameArabic} onChange={e => setCourse(x => ({...x,nameArabic:e.target.value}))} /></FormField><FormField label={pick("الاسم بالإنكليزية", "English name")}><input required value={course.nameEnglish} onChange={e => setCourse(x => ({...x,nameEnglish:e.target.value}))} /></FormField><FormField label={pick("السنة", "Year")}><select value={course.studyYear} onChange={e => setCourse(x => ({...x,studyYear:e.target.value}))}>{[1,2,3,4,5].map(x => <option key={x}>{x}</option>)}</select></FormField><FormField label={pick("الفصل", "Semester")}><select value={course.semesterNumber} onChange={e => setCourse(x => ({...x,semesterNumber:e.target.value}))}><option>1</option><option>2</option></select></FormField><FormField label={pick("نظري / أسبوع", "Theory / week")}><input type="number" min="0" value={course.theoreticalSessionsPerWeek} onChange={e => setCourse(x => ({...x,theoreticalSessionsPerWeek:e.target.value}))} /></FormField><FormField label={pick("عملي / شعبة / أسبوع", "Practical / division / week")}><input type="number" min="0" value={course.practicalSessionsPerDivisionPerWeek} onChange={e => setCourse(x => ({...x,practicalSessionsPerDivisionPerWeek:e.target.value}))} /></FormField><label className="check-field"><input type="checkbox" checked={course.requiresProjector} onChange={e => setCourse(x => ({...x,requiresProjector:e.target.checked}))} /><span>{pick("يتطلب مسلاطاً", "Requires projector")}</span></label><label className="check-field"><input type="checkbox" checked={course.requiresLab} onChange={e => setCourse(x => ({...x,requiresLab:e.target.checked}))} /><span>{pick("يتطلب مخبراً", "Requires lab")}</span></label></div></ActionForm></Card><Card title={`${pick("المقررات", "Courses")} (${courses.length})`}><DataTable headers={[pick("الرمز", "Code"), pick("المقرر", "Course"), pick("السنة", "Year"), pick("الفصل", "Semester"), pick("الجلسات", "Sessions"), pick("المتطلبات", "Requirements")]}>{courses.map(x => <tr key={x.id}><td><strong>{x.code}</strong></td><td>{pick(x.nameArabic,x.nameEnglish)}</td><td>{x.studyYear}</td><td>{x.semesterNumber}</td><td>{x.theoreticalSessionsPerWeek}T · {x.practicalSessionsPerDivisionPerWeek}P</td><td>{x.requiresLab && <Badge tone="warning">Lab</Badge>} {x.requiresProjector && <Badge tone="info">Projector</Badge>}</td></tr>)}</DataTable></Card></>}
    {tab === "offerings" && <div className="two-panel"><Card title={pick("طرح مقرر", "Create offering")}><ActionForm onSubmit={createOffering} submitLabel={pick("إنشاء الطرح", "Create offering")}><FormField label={pick("المقرر", "Course")}><select required value={offering.courseId} onChange={e => setOffering(x => ({...x,courseId:e.target.value}))}><option value="">—</option>{courses.filter(x => x.isActive).map(x => <option key={x.id} value={x.id}>{x.code} · {pick(x.nameArabic,x.nameEnglish)}</option>)}</select></FormField><FormField label={pick("الفصل", "Semester")}><select required value={offering.semesterId} onChange={e => setOffering(x => ({...x,semesterId:e.target.value}))}><option value="">—</option>{currentYear?.semesters.map(x => <option key={x.id} value={x.id}>{pick("الفصل", "Semester")} {x.number}</option>)}</select></FormField></ActionForm><div className="sub-form"><h3><UserPlus size={17} />{pick("تكليف كادر", "Assign staff")}</h3><ActionForm onSubmit={assign} submitLabel={pick("حفظ التكليف", "Assign")}><FormField label={pick("الطرح", "Offering")}><select required value={assignment.offeringId} onChange={e => setAssignment(x => ({...x,offeringId:e.target.value}))}><option value="">—</option>{offerings.map(x => <option key={x.id} value={x.id}>{x.courseCode}</option>)}</select></FormField><FormField label={pick("عضو الكادر", "Staff member")}><select required value={assignment.staffUserId} onChange={e => setAssignment(x => ({...x,staffUserId:e.target.value}))}><option value="">—</option>{staff.map(x => <option key={x.userId} value={x.userId}>{pick(x.nameArabic,x.nameEnglish)}</option>)}</select></FormField><FormField label={pick("نوع التكليف", "Teaching role")}><select value={assignment.role} onChange={e => setAssignment(x => ({...x,role:e.target.value}))}><option value="Professor">Professor · Theory</option><option value="Teacher">Teacher · Practical</option></select></FormField></ActionForm></div></Card><Card title={pick("الطروحات الحالية", "Current offerings")}>{offerings.length ? <div className="stack-list">{offerings.map(x => <div className="stack-row" key={x.id}><div><strong>{x.courseCode}</strong><span>{x.staff.length ? x.staff.map(s => `${pick(s.nameArabic,s.nameEnglish)} (${s.role})`).join(" · ") : pick("دون تكليف", "No staff assigned")}</span></div><Link2 size={18} /></div>)}</div> : <EmptyState title={pick("لا توجد طروحات", "No offerings yet")} />}</Card></div>}
    {tab === "exams" && <div className="two-panel"><Card title={pick("دورة امتحانية جديدة", "New exam period")}><ActionForm onSubmit={createExam} submitLabel={pick("إنشاء الدورة", "Create period")}><FormField label={pick("الاسم بالعربية", "Arabic name")}><input required value={exam.nameArabic} onChange={e => setExam(x => ({...x,nameArabic:e.target.value}))} /></FormField><FormField label={pick("الاسم بالإنكليزية", "English name")}><input required value={exam.nameEnglish} onChange={e => setExam(x => ({...x,nameEnglish:e.target.value}))} /></FormField><div className="two-columns"><FormField label={pick("البداية", "Starts")}><input type="date" required value={exam.startsOn} onChange={e => setExam(x => ({...x,startsOn:e.target.value}))} /></FormField><FormField label={pick("النهاية", "Ends")}><input type="date" required value={exam.endsOn} onChange={e => setExam(x => ({...x,endsOn:e.target.value}))} /></FormField></div><label className="check-field"><input type="checkbox" checked={exam.isRetake} onChange={e => setExam(x => ({...x,isRetake:e.target.checked}))} /><span>{pick("دورة تكميلية / إعادة", "Retake period")}</span></label></ActionForm><div className="sub-form"><h3>{pick("مزامنة التسجيل الإلزامي", "Mandatory enrollment sync")}</h3><ActionForm onSubmit={sync} submitLabel={pick("مزامنة", "Synchronize")} className="inline-form"><FormField label={pick("السنة الدراسية", "Study year")}><select value={syncYear} onChange={e => setSyncYear(e.target.value)}>{[1,2,3,4,5].map(x => <option key={x}>{x}</option>)}</select></FormField></ActionForm></div></Card><Card title={pick("الدورات الامتحانية", "Exam periods")}>{periods.length ? <div className="stack-list">{periods.map(x => <div className="stack-row" key={x.id}><div><strong>{pick(x.nameArabic,x.nameEnglish)}</strong><span>{formatDate(x.startsOn,language)} — {formatDate(x.endsOn,language)}</span></div>{x.isClosed ? <Badge tone="neutral">{pick("مغلقة", "Closed")}</Badge> : <button className="button button-small" onClick={() => closeExam(x.id)}><Check size={15} />{pick("إغلاق", "Close")}</button>}</div>)}</div> : <EmptyState title={pick("لا توجد دورات", "No exam periods")} />}</Card></div>}
  </>}</>;
}
