import { useEffect, useState } from "react";
import { ArrowUpRight, Bell, BookOpen, CalendarClock, CheckCircle2, DoorOpen, Users } from "lucide-react";
import { Link } from "react-router-dom";
import { useAuth } from "../auth/AuthContext";
import { Badge, Card, EmptyState, LoadingBlock, Metric, PageHeader } from "../components/ui";
import { api } from "../lib/api";
import { formatDate, isoToday, plusDays, shortTime } from "../lib/format";
import { useLanguage } from "../lib/i18n";
import type { Course, Mark, Notification, PendingUser, Room, Schedule } from "../types";

export function DashboardPage() {
  const { user, hasRole } = useAuth(); const { language, pick } = useLanguage(); const [loading, setLoading] = useState(true);
  const [schedule, setSchedule] = useState<Schedule[]>([]); const [notifications, setNotifications] = useState<Notification[]>([]); const [marks, setMarks] = useState<Mark[]>([]); const [pending, setPending] = useState<PendingUser[]>([]); const [rooms, setRooms] = useState<Room[]>([]); const [courses, setCourses] = useState<Course[]>([]);
  useEffect(() => { (async () => { try { const [nextSchedule, nextNotifications, nextCourses] = await Promise.all([api<Schedule[]>(`/api/schedules/mine?from=${isoToday()}&to=${plusDays(7)}&language=${language}`), api<Notification[]>(`/api/notifications?language=${language}`), api<Course[]>("/api/catalog/courses")]); setSchedule(nextSchedule); setNotifications(nextNotifications); setCourses(nextCourses); if (hasRole("Student")) setMarks(await api<Mark[]>("/api/marks/mine")); if (hasRole("Admin")) { const [nextPending, nextRooms] = await Promise.all([api<PendingUser[]>("/api/accounts/pending"), api<Room[]>("/api/catalog/rooms")]); setPending(nextPending); setRooms(nextRooms); } } finally { setLoading(false); } })(); }, [language, hasRole]);
  if (loading) return <LoadingBlock />;
  const unread = notifications.filter(x => !x.isRead).length; const passed = marks.filter(x => x.resultKind === "Numeric" && (x.mark || 0) >= 60).length;
  return <><PageHeader eyebrow={pick("اليوم في الكلية", "Faculty today")} title={`${pick("مرحباً", "Welcome")}, ${pick(user?.fullNameArabic || "", user?.fullNameEnglish || "").split(" ")[0]}`} description={pick("هذه لمحة سريعة عن أهم ما يحتاج انتباهك.", "Here is a focused view of what needs your attention.")} />
    <div className="metrics-grid"><Metric label={pick("محاضرات قادمة", "Upcoming sessions")} value={schedule.length} detail={pick("خلال 7 أيام", "Next 7 days")} tone="teal" /><Metric label={pick("إشعارات غير مقروءة", "Unread notifications")} value={unread} detail={notifications[0]?.title} tone="amber" />{hasRole("Student") ? <><Metric label={pick("مواد ناجحة", "Passed courses")} value={passed} detail={pick("من العلامات المنشورة", "Published results")} tone="blue" /><Metric label={pick("نتائج منشورة", "Published results")} value={marks.filter(x => x.isPublished).length} tone="rose" /></> : hasRole("Admin") ? <><Metric label={pick("حسابات بانتظار الموافقة", "Pending accounts")} value={pending.length} tone="rose" /><Metric label={pick("قاعات فعالة", "Active rooms")} value={rooms.filter(x => x.isActive).length} tone="blue" /></> : <><Metric label={pick("المقررات", "Courses")} value={courses.filter(x => x.isActive).length} tone="blue" /><Metric label={pick("محاضرات اليوم", "Sessions today")} value={schedule.filter(x => x.date === isoToday()).length} tone="rose" /></>}</div>
    <div className="dashboard-grid"><Card title={pick("الجدول القادم", "Upcoming schedule")} action={<Link className="text-link" to="/schedule">{pick("عرض الكل", "View all")} <ArrowUpRight size={15} /></Link>}>{schedule.length ? <div className="timeline-list">{schedule.slice(0, 5).map(item => <div className="timeline-item" key={`${item.seriesId}-${item.date}`}><div className="date-tile"><strong>{new Date(`${item.date}T12:00:00`).getDate()}</strong><span>{new Intl.DateTimeFormat(language === "ar" ? "ar-SY" : "en", { month: "short" }).format(new Date(`${item.date}T12:00:00`))}</span></div><div><strong>{item.title}</strong><span><CalendarClock size={14} />{shortTime(item.startsAt)}–{shortTime(item.endsAt)} · <DoorOpen size={14} />{item.roomCode}</span></div><Badge tone={item.activityType === "PracticalLecture" ? "warning" : "info"}>{item.activityType === "PracticalLecture" ? pick("عملي", "Practical") : pick("نظري", "Theory")}</Badge></div>)}</div> : <EmptyState title={pick("لا توجد محاضرات هذا الأسبوع", "No sessions this week")} />}</Card>
      <Card title={pick("آخر الإشعارات", "Latest notifications")} action={<Link className="text-link" to="/notifications">{pick("مركز الإشعارات", "Notification center")} <Bell size={15} /></Link>}>{notifications.length ? <div className="notification-preview">{notifications.slice(0, 5).map(item => <div key={item.id} className={!item.isRead ? "unread" : ""}><span className="notification-dot" /><div><strong>{item.title}</strong><p>{item.body}</p><small>{formatDate(item.createdAtUtc.slice(0, 10), language)}</small></div></div>)}</div> : <EmptyState title={pick("صندوقك هادئ", "Your inbox is clear")} />}</Card></div>
    {hasRole("Admin") && <Card className="quick-actions" title={pick("خطوات الإدارة المقترحة", "Suggested admin actions")}><div className="action-links"><Link to="/people"><Users /><span><strong>{pick("راجع الحسابات الجديدة", "Review new accounts")}</strong><small>{pending.length} {pick("بانتظارك", "waiting")}</small></span></Link><Link to="/academic"><BookOpen /><span><strong>{pick("جهّز السنة الدراسية", "Configure the academic year")}</strong><small>{courses.length} {pick("مقرر مسجل", "courses configured")}</small></span></Link><Link to="/timetable"><CheckCircle2 /><span><strong>{pick("أنشئ مسودة جدول", "Generate a timetable draft")}</strong><small>{pick("تحقق ثم انشر", "Review before publishing")}</small></span></Link></div></Card>}</>;
}
