import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, FileSpreadsheet, Search, Send, Upload } from "lucide-react";
import { useAuth } from "../auth/AuthContext";
import { ActionForm, Badge, Card, DataTable, EmptyState, FormField, LoadingBlock, PageHeader, Tabs } from "../components/ui";
import { api, json } from "../lib/api";
import { formatDateTime } from "../lib/format";
import { useLanguage } from "../lib/i18n";
import type { AcademicYear, ExamMark, ExamPeriod, Mark, StudentCourseRecord } from "../types";

const resultTone = (kind: string, mark: number | null) => kind === "Numeric" && (mark || 0) >= 60 ? "success" : kind === "NotEntered" || kind === "Withheld" ? "warning" : "danger";

export function MarksPage() {
  const { hasRole } = useAuth(); return hasRole("Student") && !hasRole("Admin", "ExamsOfficer") ? <StudentMarks /> : <ExamMarks />;
}

function StudentMarks() {
  const { language, pick } = useLanguage(); const [items, setItems] = useState<Mark[]>([]); const [loading, setLoading] = useState(true); const [appealFor, setAppealFor] = useState<string | null>(null); const [reason, setReason] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { api<Mark[]>("/api/marks/mine").then(setItems).finally(() => setLoading(false)); }, []);
  const submitAppeal = async () => { if (!appealFor || !reason.trim()) return; await api("/api/appeals", { method: "POST", ...json({ markAttemptId: appealFor, reason }) }); setAppealFor(null); setReason(""); setMessage(pick("تم إرسال الاعتراض", "Appeal submitted")); };
  return <><PageHeader eyebrow={pick("سجل أكاديمي واضح", "A clear academic record")} title={pick("علاماتي", "My marks")} description={pick("تظهر المحاولات المنشورة فقط، ويمكن الاعتراض خلال المدة المحددة.", "Only published attempts appear here, with appeals available during the configured window.")} />{message && <div className="inline-alert success"><CheckCircle2 size={17} />{message}</div>}{loading ? <LoadingBlock /> : items.length ? <Card><DataTable headers={[pick("المقرر", "Course"), pick("النتيجة", "Result"), pick("العلامة", "Mark"), pick("التاريخ", "Entered"), pick("اعتراض", "Appeal")]}>{items.map(item => <tr key={item.attemptId}><td><strong>{item.courseCode}</strong></td><td><Badge tone={resultTone(item.resultKind, item.mark)}>{item.resultKind}</Badge></td><td><strong className="mark-number">{item.mark ?? "—"}</strong><span className="muted"> / 100</span></td><td>{formatDateTime(item.enteredAtUtc, language)}</td><td>{item.isPublished && !(item.resultKind === "Numeric" && (item.mark || 0) >= 60) ? <button className="button button-small" onClick={() => setAppealFor(item.attemptId)}>{pick("اعتراض", "Appeal")}</button> : "—"}</td></tr>)}</DataTable></Card> : <Card><EmptyState title={pick("لا توجد علامات منشورة", "No published marks yet")} /></Card>}{appealFor && <Card title={pick("إرسال اعتراض", "Submit an appeal")}><ActionForm onSubmit={submitAppeal} submitLabel={pick("إرسال", "Submit")}><FormField label={pick("سبب الاعتراض", "Reason for appeal")}><textarea rows={4} required value={reason} onChange={e => setReason(e.target.value)} /></FormField></ActionForm></Card>}</>;
}

function ExamMarks() {
  const { pick } = useLanguage(); const [tab, setTab] = useState("entry"); const [years, setYears] = useState<AcademicYear[]>([]); const [periods, setPeriods] = useState<ExamPeriod[]>([]); const [records, setRecords] = useState<StudentCourseRecord[]>([]); const [marks, setMarks] = useState<ExamMark[]>([]); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [file, setFile] = useState<File | null>(null); const [importResult, setImportResult] = useState<{ imported: number; errors: Array<{ row: number; message: string }> } | null>(null);
  const [form, setForm] = useState({ studentCourseRecordId: "", examPeriodId: "", resultKind: "Numeric", mark: "", publish: true });
  const currentYear = useMemo(() => years.find(x => x.isCurrent) || years[0], [years]);
  useEffect(() => { api<AcademicYear[]>("/api/catalog/academic-years").then(setYears).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!currentYear) return; api<ExamPeriod[]>(`/api/catalog/exam-periods?academicYearId=${currentYear.id}`).then(next => { setPeriods(next); setForm(x => ({ ...x, examPeriodId: next[0]?.id || "" })); }); }, [currentYear?.id]);
  const findRecords = async () => setRecords(await api(`/api/catalog/student-course-records?search=${encodeURIComponent(search)}`));
  const loadMarks = async () => { if (form.examPeriodId) setMarks(await api(`/api/catalog/exam-marks?examPeriodId=${form.examPeriodId}&search=${encodeURIComponent(search)}`)); };
  useEffect(() => { if (tab === "history") loadMarks(); }, [tab, form.examPeriodId]);
  const enter = async () => { await api("/api/marks", { method: "POST", ...json({ studentCourseRecordId: form.studentCourseRecordId, examPeriodId: form.examPeriodId, resultKind: form.resultKind, mark: form.resultKind === "Numeric" ? Number(form.mark) : null, publish: form.publish }) }); setForm(x => ({ ...x, studentCourseRecordId: "", mark: "" })); setRecords([]); };
  const importFile = async () => { if (!file || !form.examPeriodId) throw new Error(pick("اختر ملفاً ودورة امتحانية", "Choose a file and exam period")); const data = new FormData(); data.append("file", file); setImportResult(await api(`/api/marks/imports/file?examPeriodId=${form.examPeriodId}&publish=${form.publish}`, { method: "POST", body: data })); };
  const publish = async (id: string) => { await api(`/api/marks/${id}/publish`, { method: "PUT" }); await loadMarks(); };
  return <><PageHeader eyebrow={pick("مكتب الامتحانات", "Exams office")} title={pick("إدارة العلامات", "Marks management")} description={pick("أدخل النتائج فردياً أو استورد ملفاً، ثم راجع حالة النشر.", "Enter individual results or import a file, then review publication status.")} /><Tabs tabs={[{ id: "entry", label: pick("إدخال فردي", "Individual entry") }, { id: "import", label: pick("استيراد ملف", "File import") }, { id: "history", label: pick("المحاولات", "Attempts") }]} active={tab} onChange={setTab} />{loading ? <LoadingBlock /> : <>
    <Card className="filter-card"><div className="inline-fields"><FormField label={pick("السنة الأكاديمية", "Academic year")}><select value={currentYear?.id || ""} disabled>{years.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></FormField><FormField label={pick("الدورة الامتحانية", "Exam period")}><select value={form.examPeriodId} onChange={e => setForm(x => ({ ...x, examPeriodId: e.target.value }))}><option value="">—</option>{periods.map(x => <option key={x.id} value={x.id}>{pick(x.nameArabic, x.nameEnglish)} {x.isClosed ? `(${pick("مغلقة", "closed")})` : ""}</option>)}</select></FormField></div></Card>
    {tab === "entry" && <Card title={pick("نتيجة طالب", "Student result")}><ActionForm onSubmit={enter} submitLabel={pick("حفظ النتيجة", "Save result")}><div className="search-box"><input placeholder={pick("الرقم الجامعي أو الاسم أو رمز المقرر", "University number, name, or course code")} value={search} onChange={e => setSearch(e.target.value)} /><button type="button" className="button button-secondary" onClick={findRecords}><Search size={17} />{pick("بحث", "Search")}</button></div>{records.length > 0 && <FormField label={pick("سجل المقرر", "Course record")}><select required value={form.studentCourseRecordId} onChange={e => setForm(x => ({ ...x, studentCourseRecordId: e.target.value }))}><option value="">—</option>{records.map(x => <option key={x.id} value={x.id}>{x.universityNumber} · {pick(x.studentNameArabic, x.studentNameEnglish)} · {x.courseCode}</option>)}</select></FormField>}<div className="form-grid"><FormField label={pick("نوع النتيجة", "Result kind")}><select value={form.resultKind} onChange={e => setForm(x => ({ ...x, resultKind: e.target.value }))}><option value="Numeric">Numeric</option><option value="Absent">Absent</option><option value="NotEntered">Not entered</option><option value="Withheld">Withheld</option></select></FormField>{form.resultKind === "Numeric" && <FormField label={pick("العلامة / 100", "Mark / 100")}><input type="number" min="0" max="100" step="0.01" required value={form.mark} onChange={e => setForm(x => ({ ...x, mark: e.target.value }))} /></FormField>}<label className="check-field"><input type="checkbox" checked={form.publish} onChange={e => setForm(x => ({ ...x, publish: e.target.checked }))} /><span>{pick("نشر فوراً", "Publish immediately")}</span></label></div></ActionForm></Card>}
    {tab === "import" && <Card title={pick("استيراد CSV أو XLSX", "Import CSV or XLSX")}><ActionForm onSubmit={importFile} submitLabel={pick("استيراد النتائج", "Import results")}><div className="upload-zone"><FileSpreadsheet size={32} /><strong>{pick("اختر ملف النتائج", "Choose a marks file")}</strong><p>UniversityNumber, CourseCode, Result, Mark</p><label className="button button-secondary"><Upload size={17} />{file?.name || pick("اختيار ملف", "Select file")}<input hidden type="file" accept=".csv,.xlsx" onChange={e => setFile(e.target.files?.[0] || null)} /></label></div></ActionForm>{importResult && <div className={`import-result ${importResult.errors.length ? "has-errors" : ""}`}><strong>{importResult.imported} {pick("سجل تم استيراده", "rows imported")}</strong>{importResult.errors.map(x => <p key={`${x.row}-${x.message}`}>{pick("السطر", "Row")} {x.row}: {x.message}</p>)}</div>}</Card>}
    {tab === "history" && <Card title={pick("محاولات الدورة", "Exam attempts")} action={<button className="button button-secondary" onClick={loadMarks}><Search size={16} />{pick("تحديث", "Refresh")}</button>}>{marks.length ? <DataTable headers={[pick("الطالب", "Student"), pick("المقرر", "Course"), pick("النتيجة", "Result"), pick("العلامة", "Mark"), pick("النشر", "Publication"), pick("إجراء", "Action")]}>{marks.map(x => <tr key={x.attemptId}><td><strong>{x.universityNumber}</strong><small className="table-note">{pick(x.studentNameArabic, x.studentNameEnglish)}</small></td><td>{x.courseCode}</td><td><Badge tone={resultTone(x.resultKind, x.mark)}>{x.resultKind}</Badge></td><td>{x.mark ?? "—"}</td><td><Badge tone={x.isPublished ? "success" : "warning"}>{x.isPublished ? pick("منشور", "Published") : pick("مسودة", "Draft")}</Badge></td><td>{!x.isPublished && <button className="button button-small" onClick={() => publish(x.attemptId)}><Send size={15} />{pick("نشر", "Publish")}</button>}</td></tr>)}</DataTable> : <EmptyState title={pick("لا توجد محاولات لهذه الدورة", "No attempts for this exam period")} />}</Card>}</>}</>;
}
