import { useEffect, useMemo, useState } from "react";
import { KeyRound, Search, Shuffle, UserCheck } from "lucide-react";
import { Badge, Card, DataTable, EmptyState, FormField, LoadingBlock, PageHeader, Tabs } from "../components/ui";
import { api, json } from "../lib/api";
import { useLanguage } from "../lib/i18n";
import type { AcademicYear, Division, PendingUser, Role, Staff, Student } from "../types";

const staffRoles: Role[] = ["Teacher", "Professor", "ExamsOfficer", "Admin"];

export function PeoplePage() {
  const { pick } = useLanguage(); const [tab, setTab] = useState("pending"); const [pending, setPending] = useState<PendingUser[]>([]); const [students, setStudents] = useState<Student[]>([]); const [staff, setStaff] = useState<Staff[]>([]); const [years, setYears] = useState<AcademicYear[]>([]); const [divisions, setDivisions] = useState<Division[]>([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(""); const [roles, setRoles] = useState<Record<string, Role[]>>({}); const [targets, setTargets] = useState<Record<string, string>>({}); const [password, setPassword] = useState({ userId: "", value: "" });
  const current = useMemo(() => years.find(x => x.isCurrent), [years]);
  const load = async () => { setLoading(true); try { const [p,s,st,y] = await Promise.all([api<PendingUser[]>("/api/accounts/pending"), api<Student[]>(`/api/catalog/students?search=${encodeURIComponent(search)}`), api<Staff[]>("/api/catalog/staff"), api<AcademicYear[]>("/api/catalog/academic-years")]); setPending(p); setStudents(s); setStaff(st); setYears(y); setRoles(Object.fromEntries(p.map(x => [x.id, x.roles.length ? x.roles : ["Student"]]))); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []); useEffect(() => { if (current) api<Division[]>(`/api/catalog/divisions?academicYearId=${current.id}`).then(setDivisions); }, [current?.id]);
  const toggleRole = (id: string, role: Role) => setRoles(currentRoles => ({ ...currentRoles, [id]: currentRoles[id]?.includes(role) ? currentRoles[id].filter(x => x !== role) : [...(currentRoles[id] || []), role] }));
  const approve = async (id: string) => { await api(`/api/accounts/${id}/approve`, { method: "POST", ...json({ roles: roles[id] }) }); await load(); };
  const transfer = async (studentId: string) => { const divisionId = targets[studentId]; if (!divisionId) return; await api(`/api/divisions/${divisionId}/students/${studentId}`, { method: "PUT" }); };
  const resetPassword = async () => { if (!password.userId || !password.value) return; await api(`/api/accounts/${password.userId}/password`, { method: "PUT", ...json({ newPassword: password.value }) }); setPassword({ userId:"", value:"" }); };
  return <><PageHeader eyebrow={pick("الهوية والصلاحيات", "Identity and access")} title={pick("الحسابات والطلاب", "People management")} description={pick("وافق على الحسابات، راجع الطلاب، وانقلهم بين الشعب عند الحاجة.", "Approve accounts, review students, and transfer division memberships when needed.")} /><Tabs active={tab} onChange={setTab} tabs={[{ id:"pending", label:`${pick("بانتظار الموافقة", "Pending")} (${pending.length})` }, { id:"students", label:pick("الطلاب", "Students") }, { id:"staff", label:pick("الكادر", "Staff") }, { id:"security", label:pick("كلمات المرور", "Password reset") }]} />{loading ? <LoadingBlock /> : <>
    {tab === "pending" && <Card>{pending.length ? <div className="approval-grid">{pending.map(user => { const isStudent = !user.roles.length; return <article className="approval-card" key={user.id}><div className="approval-person"><div className="avatar">{pick(user.fullNameArabic,user.fullNameEnglish).charAt(0)}</div><div><strong>{pick(user.fullNameArabic,user.fullNameEnglish)}</strong><span>{user.email}</span></div></div><div className="role-picker">{isStudent ? <label className="role-option selected"><input type="checkbox" checked readOnly /><span><strong>Student</strong><small>{pick("حساب طالب", "Student account")}</small></span></label> : staffRoles.map(role => <label className={`role-option ${roles[user.id]?.includes(role) ? "selected" : ""}`} key={role}><input type="checkbox" checked={roles[user.id]?.includes(role) || false} onChange={() => toggleRole(user.id,role)} /><span><strong>{role}</strong></span></label>)}</div><button className="button button-primary" disabled={!roles[user.id]?.length} onClick={() => approve(user.id)}><UserCheck size={17} />{pick("موافقة وتفعيل", "Approve account")}</button></article>; })}</div> : <EmptyState title={pick("لا توجد طلبات معلقة", "No pending account requests")} />}</Card>}
    {tab === "students" && <Card><div className="search-box"><input placeholder={pick("بحث بالاسم أو الرقم الجامعي", "Search by name or university number")} value={search} onChange={e => setSearch(e.target.value)} /><button className="button button-secondary" onClick={load}><Search size={17} />{pick("بحث", "Search")}</button></div><DataTable headers={[pick("الرقم الجامعي", "University no."), pick("الطالب", "Student"), pick("السنة", "Year"), pick("الحالة", "Standing"), pick("نقل الشعبة", "Division transfer")]}>{students.map(x => <tr key={x.userId}><td><strong>{x.universityNumber}</strong></td><td>{pick(x.nameArabic,x.nameEnglish)}</td><td>{x.studyYear}</td><td><Badge tone={x.standing === "Active" ? "success" : x.standing === "Repeating" ? "warning" : "neutral"}>{x.standing}</Badge></td><td><div className="table-action"><select value={targets[x.userId] || ""} onChange={e => setTargets(t => ({...t,[x.userId]:e.target.value}))}><option value="">{pick("اختر شعبة", "Choose division")}</option>{divisions.filter(d => d.studyYear === x.studyYear).map(d => <option key={d.id} value={d.id}>{pick("الشعبة", "Division")} {d.number} ({d.memberCount}/{d.capacity})</option>)}</select><button className="icon-button" disabled={!targets[x.userId]} onClick={() => transfer(x.userId)}><Shuffle size={17} /></button></div></td></tr>)}</DataTable></Card>}
    {tab === "staff" && <Card><DataTable headers={[pick("الاسم", "Name"), pick("الرقم الوظيفي", "Staff number"), pick("الأدوار", "Roles")]}>{staff.map(x => <tr key={x.userId}><td><strong>{pick(x.nameArabic,x.nameEnglish)}</strong></td><td>{x.staffNumber || "—"}</td><td>{x.roles.map(role => <Badge key={role} tone="info">{role}</Badge>)}</td></tr>)}</DataTable></Card>}
    {tab === "security" && <div className="narrow-content"><Card title={pick("إعادة تعيين كلمة مرور", "Reset a password")}><div className="action-form"><FormField label={pick("المستخدم", "User")}><select value={password.userId} onChange={e => setPassword(x => ({...x,userId:e.target.value}))}><option value="">—</option>{[...students.map(x => ({id:x.userId,name:`${x.universityNumber} · ${pick(x.nameArabic,x.nameEnglish)}`})),...staff.map(x => ({id:x.userId,name:pick(x.nameArabic,x.nameEnglish)}))].map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></FormField><FormField label={pick("كلمة المرور الجديدة", "New password")} hint={pick("سيتم إلغاء جميع جلسات التحديث النشطة.", "All active refresh sessions will be revoked.")}><input type="password" minLength={8} value={password.value} onChange={e => setPassword(x => ({...x,value:e.target.value}))} /></FormField><button className="button button-primary" onClick={resetPassword}><KeyRound size={17} />{pick("إعادة التعيين", "Reset password")}</button></div></Card></div>}
  </>}</>;
}
